name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json' # Adjust if your package-lock.json is not in the 'app' directory

      - name: Install Dependencies
        run: npm install
        working-directory: ./app # Added: Ensures npm install runs in the correct directory, as indicated by cache-dependency-path

      # Add your deployment steps here. Examples:
      # - name: Build Project
      #   run: npm run build
      #   working-directory: ./app
      #
      # - name: Deploy to Hosting Service
      #   uses: some-deployment-action@v1
      #   with:
      #     # Your deployment specific inputs
